### ISSUE TITLE
Staticly type the project and add mypi linter

### ISSUE THREAD

**Issue by c0nsol3** [Solar-network/python-crypto#11]
It's more and more common for Python libraries to be statically typed. We should aim to do the same in this library. After completion we should add `mypi` to the `format` make command so that it's easy to check if linter passes.

**Comment by sleepdefic1t** [comment]
Good idea. I'm in favor of this 👍

**Comment by sleepdefic1t** [comment]
Partially resolved in #45 

This didn't add mypi, but feel free to open a separate issue and/or PR if you'd still like to see it 👍
