### ISSUE TITLE
remove unused argument from docstring

### ISSUE THREAD

**Issue by osrn** [Solar-network/python-crypto#44]
https://github.com/Solar-network/python-crypto/blob/ce643b198060328d47cafb6d164b76be795bd493/solar_crypto/utils/crypto.py#L25-L31

nonce is not a function parameter.

**Comment by osrn** [comment]
also `sign` => `verify` needed at
https://github.com/Solar-network/python-crypto/blob/ce643b198060328d47cafb6d164b76be795bd493/solar_crypto/utils/crypto.py#L42-L46
and
https://github.com/Solar-network/python-crypto/blob/ce643b198060328d47cafb6d164b76be795bd493/solar_crypto/utils/crypto.py#L56-L60

**Comment by sleepdefic1t** [comment]
> nonce is not a function parameter.

Correct.
And near to that point, the comment in [`sign_schnorr`](https://github.com/Solar-network/python-crypto/blob/ce643b198060328d47cafb6d164b76be795bd493/solar_crypto/utils/crypto.py#L10-#L22) is incorrect.

BIP-0340 Schnorr uses a **non**-deterministic _'synthetic'_ nonce.
A string of zeroes can be passed to create a deterministic _signature_ vs the default random sig,
but the nonce in this context is not designed to be deterministic (e.g., RFC 6979).

---

> also sign => verify needed at

👍

**Comment by sleepdefic1t** [comment]
Resolved in #45
