### ISSUE TITLE
Contact Request

### ISSUE THREAD

**Issue by Bra1nsen** [Solar-network/python-crypto#48]
Firstly, I'm curious as to why your company's 'Solar Card' displays the Mastercard logo, as I couldn't find any endorsement from Mastercard. It reminds me of Centra Tech's situation. Is there something I'm missing?

Moreover, I'm intrigued by the name 'Solar Card'. Is there a connection to solar energy?

Best regards,
Paul

**Comment by alessiodf** [comment]
Please use GitHub Issues only for queries related to the relevant repository. Your question is not a technical matter related to anything connected to this repository.
